sudo: required

language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: osx
      language: generic
      env: TOXENV=py27
      osx_image: xcode8

services:
 - docker

before_install:
 - export LALSUITE_VERSION=$(python setup.py --version | sed 's/\.post.*$//')
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then docker pull quay.io/pypa/manylinux1_x86_64; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]];then docker run -e LALSUITE_VERSION -v $PWD:/project quay.io/pypa/manylinux1_x86_64 sh project/build_linux.sh; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]];then bash build_mac.sh; fi

script:
 - bash test.sh

before_deploy:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
        export PATH=$PATH:$PWD/local/bin:/Users/travis/Library/Python/2.7/bin; 
        ls; 
   fi

deploy:
  provider: pypi
  user: ahnitz
  password:
    secure: "iuXI2lUDvWfjVqvKhh1fXmMmPxOLc3wl/vW1JlSQy8XfzXhksD3iRYBsEOMuHB/X4iB9kT6J1hW7ADDBKts/6MVCptfNHx4YU9zmZ/aiHkMRGiA7FCwwtTwecoBq15jMAYbNZ3ib9WREbQXjm9SeqWfGIT3LF3JKaEqo8zdSRvKjJbTV/iMJchT7jUBShmNFc8WCFH9vo3oIBOKc4VQrQGUSGxQ9H/9fOn19QOyUGYGWsIeqev3L//B8lT/3I5aVzPTQKeB3t4cOKPG3YMNsMNEpZl/kyEZc9v52D+rINkD9zZ2MgOhlqRMa7UZtRrc0yVUOYXnAulcQSynwC5dJTxou2vuIGtBb2B+jiN8SVYs8UU3kKnItKp5LmhinKHSH9EZLNLz05YC/oUNDraYie78/eu26DaS7OK/9GP3FxWjB9ovPXrxw1jrUJe/yBrNSIeEVSTIEAU372vBy2NYWQba+GEqYf/cRzWm2VewTnjjsKJ7dw9TdmHIk+TqijZz4SfDLyXjkeZKftw9p+s6Ej7PNqgDt6diqW45U62tClxOB8k8lqITG8Xlx1nXED0dBHLsT5lCWs+Dnuph+xPhtxHCzRjmvZan/JVpjehke5NSObHVBwgffVjgOm6q0yYh8Ud/4NwdR5c1lQJQn+RrAJ/k0N3Jwz0ji2al8bPLRxSo="
  on:
    tags: true
  distributions: "bdist_wheel"
  skip_cleanup: true
